"""
PhishGuard AI 2.0 — Reports API Router
"""
import json
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from ...db.database import get_db
from ...models.scan import Scan

router = APIRouter()


@router.get("/{scan_id}")
def get_report(scan_id: int, db: Session = Depends(get_db)) -> dict:
    """
    Generate a structured JSON security analysis report for a scan.
    NOTE: PDF export is not implemented — returns JSON only.
    """
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan:
        raise HTTPException(status_code=404, detail=f"Scan {scan_id} not found")

    def parse_json_field(v):
        if not v:
            return []
        try:
            return json.loads(v)
        except Exception:
            return []

    indicators = parse_json_field(scan.indicators)
    mitre_techniques = parse_json_field(scan.mitre_techniques)
    analyst_actions = parse_json_field(scan.analyst_actions)
    timeline = parse_json_field(scan.timeline)

    verdict = scan.verdict or "Unknown"
    risk = scan.risk_score or 0.0
    severity = scan.severity or "INFORMATIONAL"
    threat_count = sum(1 for i in indicators if not i.get("passed", True))

    exec_summary = (
        f"PhishGuard AI 2.0 analysis of \'{scan.target}\' returned a verdict of {verdict.upper()} "
        f"with a risk score of {risk}/100 (severity: {severity}). "
        f"{threat_count} suspicious indicator(s) detected across {len(indicators)} checks."
    )

    if verdict == "Malicious":
        recommendations = [
            "Block this URL/domain in endpoint security controls immediately.",
            "Escalate to the security team as a confirmed threat.",
            "Notify affected users who may have visited this URL.",
            "Submit indicators to threat intelligence platforms.",
        ]
    elif verdict == "Suspicious":
        recommendations = [
            "Investigate domain registration and hosting details.",
            "Perform website content analysis if not already done.",
            "Monitor for similar domains using pattern matching.",
            "Consider blocking pending further investigation.",
        ]
    else:
        recommendations = [
            "No immediate action required.",
            "Continue monitoring for changes in domain behavior.",
        ]

    return {
        "report_version": "2.0",
        "generated_at": scan.created_at.isoformat() if scan.created_at else None,
        "scan_id": scan.id,
        "target": scan.target,
        "scan_type": scan.scan_type,
        "executive_summary": exec_summary,
        "verdict": verdict,
        "risk_score": risk,
        "confidence_score": scan.confidence_score,
        "severity": severity,
        "investigation_status": scan.investigation_status or "NEW",
        "detection_engine_version": scan.detection_engine_version or "2.0.0",
        "processing_time_ms": scan.processing_time_ms,
        "indicators_of_compromise": indicators,
        "mitre_attack_mapping": mitre_techniques,
        "analyst_actions": analyst_actions,
        "investigation_timeline": timeline,
        "analyst_notes": scan.analyst_notes or "",
        "technical_analysis": {
            "total_checks": len(indicators),
            "checks_passed": sum(1 for i in indicators if i.get("passed", True)),
            "checks_failed": threat_count,
            "detection_modules": ["URL Heuristics", "Domain Analysis", "Brand Impersonation", "Pattern Detection", "Entropy Analysis"],
        },
        "recommendations": recommendations,
        "disclaimer": "Generated by PhishGuard AI 2.0 using heuristic analysis. Review by a qualified analyst before enforcement action.",
        "pdf_export": "not_implemented",
    }
